version: '3.7'
services:
    # Laravel application
    laravel_php_fpm:
        build: ./php-fpm
        container_name: vhdm_laravel_php_fpm
        restart: always
        tty: true
        volumes:
            - "./laravel:/var/www/laravel"
        links:
            - "laravel_database"
        depends_on:
            - "laravel_database"
        environment:
            SERVICE_NAME: laravel_php_fpm
            SERVICE_TAGS: dev
            DB_PORT: ${DB_PORT}
            DB_HOST: ${DB_HOST}
        networks: 
            - vhdm_network
    # Webserver
    nginx:
        build: ./nginx
        container_name: vhdm_laravel_nginx
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_SSL_PORT:-443}:443'
        links:
            - laravel_php_fpm
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./laravel:/var/www/laravel
        restart: unless-stopped
        depends_on:
            - laravel_php_fpm
        networks: 
            - vhdm_network
    # The Database
    laravel_database:
        image: mysql:latest
        container_name: vhdm_laravel_mysql
        volumes:
            - "./database:/docker-entrypoint-initdb.d"
            - "./database/dbdata:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
        networks: 
            - vhdm_network


networks: 
    vhdm_network:
        name: vhdm_network
        driver: bridge  
              